/*You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.*/

#include<iostream>
#include<string>
using namespace std;

class Solution{
    public:
        char findTheDifference(string s, string t) {
            char res=0;
            for(char c:s) res^=c;
            for(char c:t) res^=c;
            return res;
        }
};
int main(){
    Solution solution;
    string s,t;
    cout<<"enter two strings:"<<endl;
    cin>>s>>t;
    cout<<solution.findTheDifference(s,t)<<endl;
    return 0;
}

